### ISSUE TITLE
支持延迟加载

### ISSUE THREAD

**Issue by hfcorriez** [hfcorriez/fly#24]
### 目的
- 控制加载的目录和位置
- 加快运行速度
- 减少内存占用（不加载全部）

#### 1、开启和定义
> 需要在fly.yml声明fly文件的位置和开启lazyload

```yaml
lazyload: true
path: 
  - functions/**.js
  - bss/**.js
ignore: 
  - functions/lib/**
```
#### 2、编译缓存文件
- 存储位置 `TMP/flycache/<md5 project dir>/cache.js`
- 调用命令 `fly compile`
- 编译过程
  1. 遍历所有的fly文件
  2. 和内存加载的如上位置`compiled cache`做对比，如果`md5sum`变更则`加载文件`读取配置
  3. 存储新的`md5sum`、`path`、`config`

```javascript
// compiled cache 示例文件
module.exports = {
   functionName: {
     md5sum: "",
     path: "",
     config: {
       http: {
         method: "POST",
         path: "/functions"
       }
     }
  }
}
```

#### 3、启动过程
1. 启动进程调用编译过程，等待完成
2. 运行
3. 如果监听到变更，重写 `compie cache`（开发环境）

### 代码设计

```
class FlyCache {
  // 加载指定目录的 compied cache，没有就创建空的
   init() {
  }

  // 获取所有的 cache 
  get ()
}
```
